import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import BottomBar from '@/components/BottomBar';
import { AppSidebar } from '@/components/Sidebar';
import { SidebarProvider } from '@/components/ui/sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex h-screen">
            <AppSidebar />
            <main className="w-[100vw]  md:w-[calc(100vw-256px)] overflow-auto">
              {children}
            </main>
          </div>
          <BottomBar />
        </SidebarProvider>
      </body>
    </html>
  );
}
