import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomBar from "./components/BottomBar";
import Sidebar from "./components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Sidebar />
        <div className="pb-16 sm:pb-0 sm:pl-64 pt-12">
        <main className=" mx-auto  max-w-[650px] px-4 " >
          {children}
        </main>
        </div>
       
        <BottomBar />
      </body>
    </html>
  );
}
